### ISSUE TITLE
Login with Skoda ID not working

### ISSUE THREAD

**Issue by Backes89** [nightsha-de/npm-vwconnectapi#11]
Hello there!
I am using the Skoda app and therefore I changed the config.type to "skoda" and set the credentials according to my "MySkoda" Login (Mail + password). In the example code below I removed my own credentials and placed a placeholder.

`const api = require('../npm-vwconnectapi');`

`var vwConn = new api.VwWeConnect();`
`//vwConn.setCredentials(username@email.de, password, "YourPin");`
`vwConn.setConfig("skoda");`
`vwConn.getData()`

`var intervalid = setInterval(function () {`
`   if (vwConn.finishedReading()) {`
`...`

This is the output in the console:

`$ node app.js`
`Start logging instance`
`ERROR: 400`
`ERROR: Login Failed`

The credentials are correct. The MySkoda app is working fine on my mobile with this credentials. Am I doing anything wrong in regards of the credentials or is there an error with the connection to the skoda-backend?

**Comment by pixxelfriend** [comment]
Hi, 

is `vwConn.setCredentials(....)` accidently commented out or just in the demo code snippet? 
Have you tried to set Loglevel to debug before?  `vwConn.setLogLevel("DEBUG");`

cheers

**Comment by Backes89** [comment]
In my production code I've got another row with the correct credentials and commented out the placeholder line. 

Just deleted the production line and pasted it here. So just an accident here at the snippet. The real one I am executing has my credentials.

Debug-Level is a good idea. Will try that and give more feedback later!

Cheers and thanks!

**Comment by Backes89** [comment]
Debug-Logging was active. I overwrote the parts where I think user-data specific token were generated. Hope that makes no problem.

> $ node app.js 
Start logging instance
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: parseEmailForm
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: parsePasswordForm
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: ""
DEBUG: {"date":"Wed, 14 Apr 2021 18:28:16 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"en-US","expires":"0","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"XXXXXXXXXXXXXXXXXXXXXXXXX","x-xss-protection":"1; mode=block"}
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: Error: Invalid protocol: skodaconnect:
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
ERROR: 400
ERROR: Login Failed
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false

**Comment by pixxelfriend** [comment]
Inside of your logs i saw: 
`DEBUG: Error: Invalid protocol: skodaconnect:`
It seems that the type is set to "skodaconnect" but it should be "skoda", but your sample config looks fine.

**Comment by nightsha-de** [comment]
Can you try if it works with the original ioBroker plugin? This way we could determine if it is a problem I caused while reworking the plugin to this API or if it is a general problem. It looks like the redirect url causes the problem, but this part is identical to the ioBroker plugin.

**Comment by Backes89** [comment]
> Inside of your logs i saw:
> `DEBUG: Error: Invalid protocol: skodaconnect:`
> It seems that the type is set to "skodaconnect" but it should be "skoda", but your sample config looks fine.

Yeah, I already double-checked that. Seems odd to me in the first place. As I checked the index.js of the project there was just an "skoda" entry for the login and not a skodaconnect. Will look into this tomorrow.



> Can you try if it works with the original ioBroker plugin? This way we could determine if it is a problem I caused while reworking the plugin to this API or if it is a general problem. It looks like the redirect url causes the problem, but this part is identical to the ioBroker plugin.

As I saw just now there also is a bug with nearly the same habit as this one at [Homeassistant-Skodaconnect](https://github.com/lendy007/homeassistant-skodaconnect/issues/18). Maybe the problem lays at the side of Skoda and their API?

**Comment by nightsha-de** [comment]
Did you try to use the web login (https://skodaid.vwgroup.io/account) as mentioned in one of the comments to make sure there are no new terms and conditions that need to be accepted?

**Comment by Backes89** [comment]
Yes, already tried that. There were no new Terms&Conditions, just the usual "Cookie"-header for the EU-area which I accepted.
After agreeing, still the same problem while trying to login via the node-app.

I am curious where the string for "skodaconnect" comes from? Is this a response from the server?

The code in the index.js-file has something similiar for WeCharge by VW as the full string here (Row 573): 
`if (err && err.message === "Invalid protocol: wecharge:") {`

Does the skodaconnect interface needs to be implemented due to the new iV (electrical-vehicle) range like WeCharge for VW?

**Comment by pixxelfriend** [comment]
As i can see now the login hits the `if(err) {` in line 722 and the message seems to be a message from the api itself. Currently i have no idea, what we can try. 

@nightsha-de What are your targets for this package? Do you want to keep it similar to the IOBroker Module for easier update? Last week i created a fork of yours and added some modifications to get it work. Some would be helpfull also in this package. You can have a look [here](https://github.com/pixxelfriend/npm-vwconnectapi).

**Comment by nightsha-de** [comment]
> Does the skodaconnect interface needs to be implemented due to the new iV (electrical-vehicle) range like WeCharge for VW?

Maybe this could be the solution, but probably not for all iV models, only for the MEB based ones (right now Enyaq). What model do you want to access?

As I mentioned above, I think the skodaconnect originates from the redirect url. https://github.com/nightsha-de/npm-vwconnectapi/blob/743db83798db21eb84e66e733e22a5707e84d0a3/index.js#L358

**Comment by Backes89** [comment]
I'm getting an Enyaq in the near future, but the "iV Charger Connect Pro" is already installed and a test-charge was done which is accessible in the app "Skoda powerpass" which is also linked with the Skoda-ID. I used the rfid card which was included with the charger. The Wallbox distinguishes the charges based on the rfid-card which I need to du because of the money I'll get back from my employer for the charges at home.

Is a car necessary that I can simply login with the script?

**Comment by nightsha-de** [comment]
> @nightsha-de What are your targets for this package? Do you want to keep it similar to the IOBroker Module for easier update? Last week i created a fork of yours and added some modifications to get it work. Some would be helpfull also in this package. You can have a look [here](https://github.com/pixxelfriend/npm-vwconnectapi).

Yes, my intention was to keep at least everything involved in the access to the VW servers as close to the ioBroker plugin as possible. I'm new to this whole node.js/async/promises stuff so I wanted to keep it simple for me. If something changes in the VW access, ioBroker will hopefully fix it pretty fast (as it has a larger user base) and I'll just have to merge the relevant parts from their code. Minimum effort :) We can talk about your intention with your fork (but probably better not in this ticket) and if our goals are not too different maybe you want to contribute here instead of working on your own fork. I'm happy to add you as a collaborator either way.

**Comment by nightsha-de** [comment]
> Is a car necessary that I can simply login with the script?

Maybe, I'm not sure. But as I see it currently the wall charger info is just retrieved if the config type is set to "id". So accessing the charging records wouldn't work with the Skoda setting anyway.

**Comment by Backes89** [comment]
Then I'll try the ID tag later, just in case, and will report back. 

If the extraction of the charges work I'll share my script which creates monthly Pdf Outputs of the the charges per rfid card.

**Comment by Backes89** [comment]
If I try the "iv" or "skodaconnect" I'll get as a response the HTML-Code from the register-page at VW. So this seems to be no valid tags.

Is there any possible way to get all working tags which can be used in "config". Otherwise I'll have to wait till the Enyaq is delivered to me and test further then.

**Comment by nightsha-de** [comment]
See the readme ;)

vwConn.setConfig(type)
Set the login type. "id" for the ID series. Other possible values "vw", "skoda", "seat", "audi", "vwv2" and "go".

I think we'll see additional types in the ioBroker plugin soon after the Enyaq is out on the streets.

**Comment by Backes89** [comment]
Yeah, I did look at the readme and I think I poorly expressed myself in terms of the values. I thought about if there is any chance to get all possible parameters from the API to see if there are new ones. Not the ones in the readme. Sorry about that misunderstanding.

**Comment by Backes89** [comment]
@nightsha-de Just tried your merging-branch from ioBroker and with that one the login is working fine. It results in an error that no vehicle is found, but the login itself is successful.

```
DEBUG: parseEmailForm
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: parsePasswordForm
DEBUG: ""
DEBUG: {"date":"Tue, 20 Apr 2021 06:47:50 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"en-US","expires":"0","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=XXXXXXXXXXXXXXXXXXXXXXX@apps_vw-dilab_com&relayState=XXXXXXXXXXXXXXXX&userId=XXXXXXXXXXXXXXXXX&HMAC=XXXXXXXXXXXXXXXXXXXXXXX","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"XXXXXXXXXXXXXXXXXXXXXXXXX","x-xss-protection":"1; mode=block"}
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG: Error: Invalid protocol: skodaconnect:
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
DEBUG:  Id: false HomeCharge: false ChargePay: false Stat: false Vehic: false
ERROR: Failed to get VWToken
ERROR: 400
ERROR: "{\"error\":\"invalid_grant\",\"error_description\":\"Unknown user XXXXXXXXXXXXXXX\"}"
DEBUG: Login successful
DEBUG: START getPersonalData()
DEBUG: getPersonalData
DEBUG: getPersonalData: "{\"firstName\":\"XXX\",\"lastName\":\"XXX\",\"salutation\":\"SALUTATION:MR\",\"dateOfBirth\":\"XXX\",\"addresses\":[{\"country\":\"DE\",\"usageType\":\"ADDRESS_USAGE_TYPE:HOME_ADDRESS\",\"uuid\":\"XXXXXXXXXXXX\",\"primary\":true,\"name\":\"XXX\",\"street\":\"XXX\",\"housenumber\":\"12345\",\"zipCode\":\"XXX\",\"city\":\"XXX\",\"_updated\":\"2021-04-15T06:24:29.951Z\",\"type\":\"ADDRESS_TYPE:v1.address.GermanAddress\"}],\"preferredLanguage\":\"de\"}"
DEBUG: START getVehicles
ERROR: 400
DEBUG: getVehicles: {"error":{"errorCode":"gw.error.authentication","description":"Malformed request"}}
INFO:  No Vehicles found
ERROR: Get Vehicles Failed
```

**Comment by nightsha-de** [comment]
Thank you for opening https://github.com/TA2k/ioBroker.vw-connect/issues/86 to request the Skoda Wallbox support. Since I'll be monitoring the ioBroker project for relevant changes anyway I'm closing this issue for now.

**Comment by nightsha-de** [comment]
I took over the Skoda iV connect from the ioBroker plugin. Anyone able to give it a try? See #19
