### ISSUE TITLE
log has no warn method

### ISSUE THREAD

**Issue by StefanSchoof** [nightsha-de/npm-vwconnectapi#14]
At 
https://github.com/nightsha-de/npm-vwconnectapi/blob/0535641b1916daa0de128def65bf56581b33c5bf/index.js#L547
the `log.warn` method is used, but the log class defines no warn method.

**Comment by nightsha-de** [comment]
Can you test it please? Apparently I don't run in any of this warning logs with my ID.

**Comment by StefanSchoof** [comment]
Thanks, it works. I currently do not understand why i get in some requests this warning. I need further investigation to find the root cause.
