### ISSUE TITLE
Hang/Loop within getData()

### ISSUE THREAD

**Issue by gk998** [nightsha-de/npm-vwconnectapi#22]
I have an id.charger pro and want to export my charging progresses. I don't have an id or any other vw car. I found a script, that basically fetches the data using npm-vwconnectapi: 
vwConn.setCredentials(email, password, "YourPin");
vwConn.setConfig("id");
vwConn.getData()

I can fetch all the charging data, but after that it hangs. I enabled debug logging and get: 
DEBUG:  Id: false HomeCharge: true ChargePay: true Stat: true Vehic: true
DEBUG:  Id: false HomeCharge: true ChargePay: true Stat: true Vehic: true
DEBUG:  Id: false HomeCharge: true ChargePay: true Stat: true Vehic: true
(endless)

Could it be because Id: is false?

**Comment by nightsha-de** [comment]
Yes, this could be the reason. Seems you are the first one to try this without an ID. Can you please try and check if the change in pull request #23 solves your problem?

**Comment by gk998** [comment]
That works, thanks!

**Comment by nightsha-de** [comment]
Great, I'll merge it in the main branch.
